version: '2.0'

volumes:
  mongodata:

networks:
  timesheet:
    driver: bridge

services:
  timesheet_mongodb:
    image: mvertes/alpine-mongo:3.6.5-0
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - timesheet

  timesheet_userservice:
      image: timesheet_service:1.0
      build: ./server/
      links:
        - timesheet_mongodb      
      environment:
        PORT: 80
        MONGO_URL: 'mongodb://timesheet_mongodb:27017/timesheet'      
      expose:
        - 80        
      ports:
        - "80:80"
      networks:
        - timesheet
